### ISSUE TITLE
Embedded ActiveMQ does not work with Grails 2.2.0.RC2

### ISSUE THREAD

**Issue by pledbrook** [domix/grails-activemq#1]
I'm seeing the error

    Caused by ClassNotFoundException: org.apache.activemq.broker.region.ConnectorStatistics

The weird thing is that activemq-core is definitely on the runtime classpath, so I have no idea why this is happening. It must be related to the way the classes are loaded by Spring, but I'm lost.

Actually, it's happening with 2.1.1 as well. I suspect a change in Spring behaviour, but I don't know.

**Comment by domix** [comment]
I just released 0.5 version, i think the issue is solved
