### ISSUE TITLE
activemq:0.4.1 Issue with grails 2.4.2[ApplicationHolder class in ActiveMQUtils]

### ISSUE THREAD

**Issue by kiranvennampelli** [domix/grails-activemq#2]
In grails 2.4.2 version I am using activemq0.4.1 plugin,this plugin has ActiveMQUtils class which is using ApplicationHolder class which is deprecated in grails 2.4.2, How can I upgrade/modify  this plugin? Please suggest

**Comment by sureshabs** [comment]
Is there any update on this release ?

**Comment by domix** [comment]
Sorry guys, I've been very busy, I'll release a new version this weekend

**Comment by domix** [comment]
This weekend the Grails plugins system (repo & portal) were broken

**Comment by domix** [comment]
I just released 0.5 version

**Comment by sureshabs** [comment]
thanks domix
